### ISSUE TITLE
The example proxy doesn't work on some servers

### ISSUE THREAD

**Issue by gioiann** [Sandertv/gophertunnel#1]
I tried compiling the example proxy in main.go and it works great on all the servers i've tried except on mco.cubecraft.net:19132 for some strange reason. Also most of the server will disconnect you for login timeout if it doesn't login fast enough but I easily fixed that by moving [raknet.Dial](https://github.com/Sandertv/gophertunnel/blob/master/minecraft/dial.go#L76) after the [authchain](https://github.com/Sandertv/gophertunnel/blob/master/minecraft/dial.go#L89)

I don't have the error it gives when connecting to cubecraft right now, i will post it later. You can try for yourself anyway.

**Comment by Sandertv** [comment]
I found the issue of raknet.Dial before authchain earlier, but forgot pushing that. Thanks for opening an issue.
For Cubecraft not working, I'm looking into it. There are a select few of other servers that also seem not to accept the RakNet handshake.

**Comment by gioiann** [comment]
I just realized that's the first issue :rofl:
Thank you for creating such an awesome library :smiley: !
I will let you know if i find out why it does that on cubecraft.

Btw, if you join play.lbsg.net:19132 it will spam an error in the console about the pong packet being wrongly encoded by lbsg which is right but there is no need to spam it like that, it's just annoying. Should i open another issue for that?

**Comment by Sandertv** [comment]
I'm aware of that too, that's an LBSG issue, but those errors should be silenced either way. Could you open an issue on https://github.com/Sandertv/go-raknet for that? Thanks!

**Comment by Sandertv** [comment]
So on the latest commit, connection to Cubecraft appears to work. Connection to some other servers, in particular servers that use a Nemisys proxy in front of it, seems not to work yet.

**Comment by gioiann** [comment]
I can now join CubeCraft but after a few seconds it seems like the server is not receiving client packets anymore as i'm not able to type messages in chat nor join games. The client still receives packets as i can see players moving

**Comment by Sandertv** [comment]
Hmmm, I can reproduce. Does this issue happen to you on any other servers?

**Comment by gioiann** [comment]
No, i only tested on mojang featured servers and a few pocketmine servers and this only happens on cubecraft. I think the problem has something to do with raknet reliability. Try only sending unreliable packets to cubecraft just to make sure that's the problem.

**Comment by Sandertv** [comment]
It seems like Cubecraft doesn't send NACK packets when it misses datagrams, causes the entire thing to be throttled. I'll make it so that the client does that by itself too, like the official RakNet does.

**Comment by Sandertv** [comment]
@gioiann the latest commit pushed to gophertunnel appears to fix the issue. Please try it and let me know if it works properly now.

**Comment by gioiann** [comment]
Now this happens when i join

```panic: interface conversion: interface {} is nil, not *raknet.packet

goroutine 34 [running]:
github.com/sandertv/go-raknet.(*Conn).resend(0xc00014e000, 0xc000d1e000, 0x5, 0x8, 0x141d599d1, 0xaa0a00)
 /home/gio/go/pkg/mod/github.com/sandertv/go-raknet@v1.4.0/conn.go:751 +0x75a
github.com/sandertv/go-raknet.(*Conn).Write(0xc00014e000, 0xc000022160, 0x9, 0xa, 0x0, 0x0, 0x0)
 /home/gio/go/pkg/mod/github.com/sandertv/go-raknet@v1.4.0/conn.go:201 +0x8a1
github.com/sandertv/go-raknet.newConn.func1(0xc00014e000)
 /home/gio/go/pkg/mod/github.com/sandertv/go-raknet@v1.4.0/conn.go:160 +0x58d
created by github.com/sandertv/go-raknet.newConn
 /home/gio/go/pkg/mod/github.com/sandertv/go-raknet@v1.4.0/conn.go:147 +0x467```

**Comment by Sandertv** [comment]
Apologies, I pushed the wrong raknet commit. Try now.

**Comment by gioiann** [comment]
Since the resendDelay is 25ms by default, packets are sent twice as the latency between me and the server is way more than 25ms so there is no way to receive an ack before the packet is sent again. So I increased the resendDelay to 1 second but it's still not working, same problem

**Comment by Sandertv** [comment]
I think I've found a fix that works reliably now. It just needs some improvements to reduce unneeded packet resending.

**Comment by Sandertv** [comment]
Just pushed another new tag with fixes that should make this work. This time I've done some quite extensive testing and so far I haven't run into the issue.

**Comment by gioiann** [comment]
Yes, it's working but how do you know packets aren't being resent for no need wasting bandwidth?

**Comment by Sandertv** [comment]
It's never going to be certain if packets will still arrive or not. Waiting longer with resending packets means you'll get visible delays in-game, whereas waiting too short means you'll resend packets when it's over not needed, however it does mean that there are no delays in-game. Right now, I've set the delay until a packet is resent to `latency * 2 + 10` milliseconds. That should be high enough for acknowledgements to arrive within time.

**Comment by gioiann** [comment]
You could improve it by making the minResendDelay higher if the server sends NACKs

**Comment by Sandertv** [comment]
Yeah, there's some work to do still.

**Comment by gioiann** [comment]
I've been getting this error really often, expecially on mineplex. When this happens a temporary "fix" is restarting the proxy but eventually it will happen again.
```
error reading from client connection: error reading batch: invalid packet checksum: d6f4aaa48ed69500 should be 228fc984d0749b49
```
This error message can be either from listener.go or dial.go since it's the same for  both. I found out it's from [there](https://github.com/Sandertv/gophertunnel/blob/master/minecraft/dial.go#L147)

So either the server is not encrypting properly (and i don't think so since it works without proxy) or the proxy is doing something wrong.
